### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Angry-Chick** [Angry-Chick/carefree#2]
###  New features
- [x] 暂时使用 jwt 进行鉴权，在 api gateway 中进行集中鉴权
- [ ] 接口使用 https 协议
- [ ] 微服务的 http 端口实现一些 rpc 状态的检测
- [ ] 增加服务发现功能（nacos）
- [ ] 支持第三方登录 oauth2.0
- [ ] 增加 RPC 服务之间鉴权(jwt)
- [ ] 使用中间层 bufferstore 缓存数据
- [ ] 写出生成器，生成框架代码
- [ ] IAM 进行角色的权限控制
### Refactor
- [ ] 密码结构不直接存储到 proto 中，加密存储到关联表中
- [ ] 修改密码使用单独的接口
- [ ] 使用更合适的数据库（可以考虑云数据库）

### New features 
- [X] web 书签 
- [X] TODO list
- [X] note 
- [ ] 搜索框

    参考 https://a.maorx.cn/ 尽量采用极简风格的设计。可以参考 Alfred 快速打开书签的功能
- [ ] 使用卡片式 ui
### Refactor
- [ ] 取消登录注册页面，用户不登录时可以使用一些基础功能
- [ ] 前端使用 proto 与后端进行通讯
- [ ] 优化引用路径    
    可以考虑使用 protojs。或者手动写轮子
- [ ] 组件重新设计。
